version: '3.1'
services:
  baby-relay:
    container_name: 'relay'
    image: baby-relay:latest
    ports:
      - "8443:8443"
      - "1935:1935"
      - "19350:19350"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/stunnel:/etc/stunnel
    restart: unless-stopped
